// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: '../',
    map: {
      '*': {
        game: 'src/game',
        snake: 'src/snake',
        utils: 'src/utils',
        pair: 'src/pair',
        grid: 'src/grid',
        foodqueue: 'src/foodqueue',
        queue: 'src/queue',
        graph: 'src/graph',
        graphics2: 'src/graphics2',
        graphics: 'src/graphics'
      }
    }
  });

}).call(this);
