// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: '../',
    paths: {
      'jquery': 'lib/jquery'
    },
    map: {
      '*': {
        world: 'src/world',
        game: 'src/game',
        game2: 'src/game2',
        game3: 'src/game3',
        snake: 'src/snake',
        utils: 'src/utils',
        pair: 'src/pair',
        grid: 'src/grid',
        cube: 'src/cube',
        foodqueue: 'src/foodqueue',
        queue: 'src/queue',
        graph: 'src/graph',
        graphics2: 'src/graphics2',
        graphics3: 'src/graphics3',
        graphics: 'src/graphics'
      }
    }
  });

}).call(this);
