// Generated by CoffeeScript 1.3.3
(function() {

  window.show = function(variable, message) {
    if (message) {
      console.log(message);
    }
    console.log(variable);
    return console.log('');
  };

  window.assert = function(exp, message) {
    var callerLine, clean, err, getErrorObject, index;
    if (exp) {
      return;
    }
    getErrorObject = function() {
      try {
        throw Error('');
      } catch (err) {
        return err;
      }
    };
    err = getErrorObject();
    window.err = err;
    callerLine = err.stack.split("\n")[4];
    index = callerLine.indexOf("at ");
    clean = callerLine.slice(index + 2, callerLine.length).split(':')[2];
    if (message) {
      console.error("Testing: " + message);
    }
    console.error("Assertion failed at line " + clean);
    return console.log('');
  };

}).call(this);
