// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      'jquery': 'lib/jquery'
    }
  });

  require(['jquery', 'src/game2'], function($, Game2) {
    return new Game2('#game');
  });

}).call(this);
