// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      'jquery': 'lib/jquery'
    },
    shim: {
      'lib/Three.js': {
        'exports': 'THREE'
      }
    }
  });

  require(['src/game'], function(Game) {
    var game, gameWrapper;
    gameWrapper = document.getElementById('game');
    game = new Game(gameWrapper);
    return game.run();
  });

}).call(this);
