// Generated by CoffeeScript 1.3.3
(function() {
  'import https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js';

  'import game';

  'import queue';

  'import snake';

  'import grid';

  'import graphics';

  'import pair';

  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TestGrid = (function(_super) {

    __extends(TestGrid, _super);

    function TestGrid() {
      return TestGrid.__super__.constructor.apply(this, arguments);
    }

    TestGrid.before = function() {
      $('head').append('<link rel="stylesheet" type="text/css" href="../snake.css" />');
      return this.game = new SNAKE.Game({
        debugStep: true
      });
    };

    TestGrid.prototype.testClosestFood = function() {
      this["class"].game.grid.dropFood();
      this["class"].game.grid.dropFood();
      this["class"].game.grid.dropFood();
      this["class"].game._gameLoop();
      return console.log('doing test closest food!');
    };

    TestGrid.prototype.testModuloBoundaries = function() {
      return console.log('doing test modulo boundaries!');
    };

    return TestGrid;

  })(Test);

}).call(this);
