// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['src/queue'], function(Queue) {
    var FoodQueue;
    return FoodQueue = (function(_super) {

      __extends(FoodQueue, _super);

      function FoodQueue(grid, maxFood, items) {
        this.grid = grid;
        this.maxFood = maxFood;
        FoodQueue.__super__.constructor.call(this, items);
      }

      FoodQueue.prototype.foodCount = 0;

      FoodQueue.prototype.enqueue = function(item) {
        FoodQueue.__super__.enqueue.call(this, item);
        this.grid.squareAt(item).food.show();
        this.foodCount += 1;
        if (this.foodCount > this.maxFood) {
          return this.dequeue();
        }
      };

      FoodQueue.prototype.dequeue = function() {
        var foodPos;
        while (!this.grid.squareHasFood(this.peek())) {
          FoodQueue.__super__.dequeue.call(this);
        }
        foodPos = FoodQueue.__super__.dequeue.call(this);
        this.grid.squareAt(foodPos).food.hide();
        this.foodCount -= 1;
        return foodPos;
      };

      return FoodQueue;

    })(Queue);
  });

}).call(this);
