// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['queue'], function(Queue) {
    var FoodQueue;
    return FoodQueue = (function(_super) {

      __extends(FoodQueue, _super);

      function FoodQueue(grid, items) {
        this.grid = grid;
        FoodQueue.__super__.constructor.call(this, items);
      }

      FoodQueue.prototype.enqueue = function(item) {
        FoodQueue.__super__.enqueue.call(this, item);
        return this.grid.registerFoodAt(item);
      };

      FoodQueue.prototype.dequeue = function() {
        var foodPos;
        while (!this.grid.squareHasFood(this.peek())) {
          FoodQueue.__super__.dequeue.call(this);
        }
        foodPos = FoodQueue.__super__.dequeue.call(this);
        return this.grid.unregisterFoodAt(foodPos);
      };

      return FoodQueue;

    })(Queue);
  });

}).call(this);
