// Generated by CoffeeScript 1.3.3
(function() {

  window.Game = (function() {

    function Game() {}

    Game.debugPrint = false;

    Game.debugStep = false;

    Game.log = function(message) {
      if (!Game.debugPrint) {
        return;
      }
      return console.log(message);
    };

    return Game;

  })();

}).call(this);
