// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['jquery', 'src/snake', 'src/utils', 'src/foodqueue'], function($, Snake, Utils, FoodQueue) {
    var Game;
    return Game = (function() {

      function Game(selector, settings) {
        var defaults, option, value;
        if (settings == null) {
          settings = {};
        }
        this._dropFood = __bind(this._dropFood, this);

        this._gameLoop = __bind(this._gameLoop, this);

        this.stepCount = 0;
        this.stepsPerFood = 20;
        this.timeStepRate = 100;
        this.gameIntervalID = null;
        defaults = {
          debugPrint: false,
          debugStep: false
        };
        for (option in defaults) {
          value = defaults[option];
          this[option] = value;
          if (settings[option]) {
            this[option] = settings[option];
          }
        }
      }

      Game.prototype._startGame = function() {
        this.grid.makeWorld();
        this.snake = new Snake(this, this.grid);
        this.stepCount = 0;
        if (this.debugStep) {
          return this.setupGameStep();
        }
        this.gameIntervalID = setInterval(this._gameLoop, this.timeStepRate);
        return this._gameLoop();
      };

      Game.prototype._gameLoop = function() {
        if ((this.stepCount % this.stepsPerFood) === 0) {
          this._dropFood();
        }
        if (!this.snake.move()) {
          return;
        }
        this.graphics.update();
        return this.stepCount += 1;
      };

      Game.prototype._dropFood = function(pos) {
        if (pos == null) {
          pos = Utils.randPair(this.grid.squaresX - 1, this.grid.squaresY - 1);
        }
        return this.foodItems.enqueue(pos);
      };

      Game.prototype.restart = function() {
        clearInterval(this.gameIntervalID);
        this.snake = this.grid.snake = new Snake(this, this.grid);
        this.foodItems.foodCount = 0;
        this.grid.destroyWorld();
        this.graphics.update();
        this._startGame();
        return false;
      };

      Game.prototype.setupGameStep = function() {
        var _this = this;
        $(window).keydown(function(event) {
          if (event.keyCode === 83) {
            return _this._gameLoop();
          }
        });
        return console.warn('Debug stepping is active. Press s to move a time step.');
      };

      Game.prototype.log = function(message) {
        if (!this.debugPrint) {
          return;
        }
        return console.log(message);
      };

      return Game;

    })();
  });

}).call(this);
