// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['game', 'cube', 'utils', 'graphics3'], function(Game, Cube, Utils, Graphics3) {
    var Game3;
    return Game3 = (function(_super) {

      __extends(Game3, _super);

      function Game3(selector, settings) {
        if (settings == null) {
          settings = {};
        }
        Game3.__super__.constructor.call(this, selector, settings);
        this.cube = new Cube(this);
        this.maxFood = 24;
        this.foodItems = null;
        this.graphics = new Graphics3(this, this.cube);
        this._startGame();
      }

      Game3.prototype.dropFood = function() {
        var index;
        index = Utils.randInt(0, 5);
        return this.cube.faces[index].dropFood();
      };

      return Game3;

    })(Game);
  });

}).call(this);
