// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Graphics;
    return Graphics = (function() {

      function Graphics(game) {
        this.game = game;
      }

      return Graphics;

    })();
  });

}).call(this);
