// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Graphics;
    return Graphics = (function() {

      function Graphics(game, grid) {
        this.game = game;
        this.grid = grid;
        this.grid.setup(this);
      }

      return Graphics;

    })();
  });

}).call(this);
