// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SNAKE.Grid3 = (function(_super) {

    __extends(Grid3, _super);

    function Grid3(game, snake) {
      this.game = game;
      this.snake = snake;
      this.maxFood = 16;
    }

    return Grid3;

  })(SNAKE.Grid);

}).call(this);
