// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Queue;
    return Queue = (function() {

      function Queue(items) {
        if (items == null) {
          items = [];
        }
        this._queue = items;
      }

      Queue.prototype.enqueue = function(item) {
        return this._queue.push(item);
      };

      Queue.prototype.dequeue = function() {
        if (!this.size()) {
          return null;
        }
        return this._queue.shift();
      };

      Queue.prototype.size = function() {
        return this._queue.length;
      };

      Queue.prototype.peek = function() {
        return this._queue[0];
      };

      Queue.prototype.back = function() {
        return this._queue[this.size() - 1];
      };

      Queue.prototype.isEmpty = function() {
        return this._queue.length === 0;
      };

      Queue.prototype.toString = function() {
        var string;
        string = this._queue.reverse().toString();
        this._queue.reverse();
        return string;
      };

      return Queue;

    })();
  });

}).call(this);
