// Generated by CoffeeScript 1.3.3
(function() {

  define(['pair'], function(Pair) {
    var Utils;
    return Utils = (function() {

      function Utils() {}

      Utils.randInt = function(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
      };

      Utils.randPair = function(min1, max1, min2, max2) {
        var randX, randY;
        if (arguments.length === 2) {
          randX = this.randInt(0, min1);
          randY = this.randInt(0, max1);
        } else {
          randX = this.randInt(min1, max1);
          randY = this.randInt(min2, max2);
        }
        return new Pair(randX, randY);
      };

      Utils.concat = function(array1, array2) {
        return array1.push.apply(array1, array2);
      };

      Utils.argsToArray = function(args) {
        return Array.prototype.slice.call(args);
      };

      Utils.minArray = function() {
        var args, lengths, minLength;
        if (!arguments.length) {
          return Infinity;
        }
        args = Utils.argsToArray(arguments);
        lengths = args.map(function(array) {
          return array.length;
        });
        minLength = Math.min.apply(null, lengths);
        return args[lengths.indexOf(minLength)];
      };

      Utils.equivalenceId = (function() {
        var dataAdded, dataIds, id;
        id = 0;
        dataIds = [];
        dataAdded = [];
        return function(datum) {
          var index;
          index = dataAdded.indexOf(datum);
          if (index === -1) {
            dataAdded.push(datum);
            dataIds.push(id);
            return id++;
          }
          return dataIds[index];
        };
      })();

      return Utils;

    }).call(this);
  });

}).call(this);
